MACOSX_DEPLOYMENT_TARGET:
  - '10.11'  # [osx]
macos_min_version:
  - '10.11'  # [osx]
c_compiler_version:                       # [ppc64le]
  - '8'                                   # [ppc64le]
cxx_compiler_version:                     # [ppc64le]
  - '8'                                   # [ppc64le]

pin_run_as_build:
  # libuv is missing run_exports
  libuv:
    max_pin: x.x
    min_pin: x.x.x
