{% set version = "12.16.0" %}

package:
  name: nodejs
  version: {{ version }}

source:
  fn: node-v{{ version }}.tar.gz
  url: https://nodejs.org/dist/v{{ version }}/node-v{{ version }}.tar.gz  # [not win]
  sha256: ae2dfe74485d821d4fef7cf1802acd2322cd994c853a2327c4306952f4453441  # [not win]
  url: https://nodejs.org/dist/v{{ version }}/node-v{{ version }}-win-x64.zip  # [win]
  sha256: 9a590dd064b491fbd40b366ae4a119fe6cef516a25fb4d78d7c2a64b37574da8  # [win]
  patches:
    - linux-librt.patch  # [not win]
    - no-libatomic-mac.patch  # [osx]
    - cinttypes.patch  # [linux]

build:
  number: 0
  ignore_prefix_files:
    - bin/node

requirements:
  build:
    - {{ compiler('c') }}  # [not win]
    - {{ compiler('cxx') }}  # [not win]
    - python 2.7  # [not win]
    - git  # [linux]
    - make  # [linux]
    - pkg-config  # [not win]
  host:
    - vs2015_runtime  # [win]
    - icu  # [not win]
    - libuv >=1.34  # [not win]
    - openssl >=1.1.1d   # [not win]
    - zlib  # [not win]
  run:
    - vs2015_runtime  # [win]
    - icu  # [not win]
    - libuv  # [not win]
    - openssl >=1.1.1d  # [not win]
    - zlib  # [not win]
  run_constrained:  # [osx]
    - __osx >={{ MACOSX_DEPLOYMENT_TARGET|default("10.9") }}  # [osx]

test:
  commands:
    - node -h
    - node -v
    - npm version
    - npm install -h
    - npm config get prefix -g
    - test $(echo "console.log(1 + 3)" | node) == 4  # [not win]

about:
  home: https://nodejs.org/
  license: MIT
  license_file: LICENSE
  summary: a platform for easily building fast, scalable network applications

extra:
  recipe-maintainers:
    - minrk
    - msarahan
    - pelson
