{% set version = "14.15.4" %}

# NODE_MODULE_VERSION set in src/node_version.h
{% set NODE_MODULE_VERSION = 83 %}

package:
  name: nodejs
  version: {{ version }}

source:
  fn: node-v{{ version }}.tar.gz
  url: https://nodejs.org/dist/v{{ version }}/node-v{{ version }}.tar.gz  # [not win]
  sha256: 8610d81b2d4afc3a79afbe6209d510125131c45cae22cac63bb767dcfec1cbf0  # [not win]
  url: https://nodejs.org/dist/v{{ version }}/node-v{{ version }}-win-x64.zip  # [win]
  sha256: b2a0765240f8fbd3ba90a050b8c87069d81db36c9f3745aff7516e833e4d2ed6  # [win]
  patches:
    - linux-librt.patch  # [not win]
    - cinttypes.patch  # [linux]

build:
  number: 1
  # Prefix replacement breaks in the binary embedded configurations.
  detect_binary_files_with_prefix: false
  run_exports:
    - {{ pin_subpackage('nodejs', max_pin='x') }}

requirements:
  build:
    - {{ compiler('c') }}  # [not win]
    - {{ compiler('cxx') }}  # [not win]
    - python 3.7  # [not win]
    - git  # [linux]
    - ninja  # [not win]
    - pkg-config  # [not win]
  host:
    - icu >=65  # [not win]
    - libuv >=1.33  # [not win]
    - openssl  >=1.1.1d  # [not win]
    - zlib  # [not win]
  run:
    - icu  # [not win]
    - libuv  # [not win]
    - openssl  # [not win]
    - zlib  # [not win]
  run_constrained:   # [osx]
    - __osx >={{ MACOSX_DEPLOYMENT_TARGET|default("10.9") }}  # [osx]

test:
  commands:
    - node -h
    - node -v
    - npm version
    - npm install -h
    - npm config get prefix -g
    - test $(echo "console.log(1 + 3)" | node) == 4  # [not win]
    - test -f $PREFIX/lib/libnode.{{ NODE_MODULE_VERSION }}.dylib  # [osx]
    - test -f $PREFIX/lib/libnode.so.{{ NODE_MODULE_VERSION }}  # [linux]

about:
  home: https://nodejs.org/
  license: MIT
  license_file: LICENSE
  summary: a platform for easily building fast, scalable network applications

extra:
  recipe-maintainers:
    - minrk
    - msarahan
    - pelson
    - blink1073
    - xhochy
